services:
  - type: static
    name: noizz25frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: VITE_API_BASE_URL
        value: https://noizz25backend.onrender.com

